spring.application.name=smart-campus-backend
server.port=${SERVER_PORT:8080}
spring.config.import=optional:file:./.env.properties,optional:file:./backend/.env.properties,optional:file:./.env,optional:file:./backend/.env
spring.data.mongodb.uri=mongodb+srv://weerashinghatheshan_db_user:JkgMaNpwy5javzml@cluster0.23mhwzb.mongodb.net/smart_campus?appName=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}
app.security.admin-username=${ADMIN_USERNAME:admin}
app.security.admin-password=${ADMIN_PASSWORD:admin123}

spring.security.oauth2.client.registration.google-user.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google-user.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google-user.scope=openid,profile,email
spring.security.oauth2.client.registration.google-user.provider=google

spring.security.oauth2.client.registration.google-technician.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google-technician.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google-technician.scope=openid,profile,email
spring.security.oauth2.client.registration.google-technician.provider=google
